import "@/app/globals.css"
import Header from "@/app/components/header"
import Footer from "@/app/components/footer"
export const metadata = {
  title: 'SC TECH (2025) LIMITED PARTNERSHIP',
  description: 'Generated by Next.js',
  icons: {
    icon: "/logo1.svg",
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
